# Peer identity: /p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ
# Peer role: bootstrap

# whether to register handlers on the messages and log them
InstanceID = 0
ListenMessages = true

[P2P]
P2PKey          = "CAESQKFtiMAqd2c8bQ/mfPStxViY970MNtWUVWdn44rUoQXAfv7ztSQ9nLeqliXrkuqKi3XUObyAfH+Py3eMbHFvIpM="
ListenAddresses   = ["/ip4/0.0.0.0/tcp/23000"]
# Overwrite p2p boostrap nodes
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]
DiscoveryNamespace = 'shutter-local'

[P2P.FloodSubDiscovery]
Enabled = true
Interval = 10
Topics = []

[Metrics]
Enabled = false
Host = '[::]'
Port = 9100
