# Peer identity: /p2p/12D3KooWQHp6UiLdi46qyettnq664LkjqwFv8yKhxA1tLHi1C73c
# Ethereum address: 0x03C82916552440f803b6284B40a0d64C5eb4E779

InstanceID = 0
# If it's empty, we use the standard PG_ environment variables
DatabaseURL		= "postgres://postgres@db:5432/keyper-3"
HTTPEnabled = false
HTTPListenAddress = ':3000'

[P2P]
P2PKey = 'CAESQH9VL1y+iPWZeVK+ga3pIy33JNpkX0bdKyON/45ut+gG1wudK44qlCp/pcE40rEk4NljSzkfHs7Ez86wIfN8YEc='
ListenAddresses   = ["/ip4/0.0.0.0/tcp/23000"]
# Overwrite p2p boostrap nodes
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]
DiscoveryNamespace = 'shutter-local'

[Ethereum]
PrivateKey = 'e728f5f1254b4c645ff2f2181fc114f4bb6ab2a995df2f6d97f1f220f5936898'
# The JSON RPC endpoint where the contracts are accessible
ContractsURL = 'http://127.0.0.1:8555/'
# Contract source directory
DeploymentDir       = "/deployments/dockerGeth/"
# The layer 1 JSON RPC endpoint
EthereumURL         = "http://geth:8545/"

[Shuttermint]
ShuttermintURL		= "http://chain-3-validator-1:26657"
ValidatorPublicKey = "feca1dfd7fab3877c05d99e0e900dd1fc2c17d88d82750bda6ff0b11b41375b3"
EncryptionKey = '13c24d4a50e53bdb4cf8ae328491fd10fbf1bc0118ff6adad1340fa77eaf9c3c'
DKGPhaseLength = 8
DKGStartBlockDelta = 200

[P2P.FloodSubDiscovery]
Enabled = false
Interval = 10
Topics = []

[Metrics]
Enabled  = true
Host     = "[::]"
Port     = 9100
